update=9/11/2019 1:05:05 PM
version=1
last_client=kicad
[general]
version=1
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=Encoder.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=C:/Program Files/KiCad/share/kicad/library/arduino-kicad-library-master/Arduino.pretty;E:/Zharfan's Document/Project Document/Gowin/circuit/library
[eeschema/libraries]
LibName1=C:/Program Files/KiCad/share/kicad/library/arduino-kicad-library-master/arduino
LibName2=power
LibName3=device
LibName4=switches
LibName5=relays
LibName6=motors
LibName7=transistors
LibName8=conn
LibName9=linear
LibName10=regul
LibName11=74xx
LibName12=cmos4000
LibName13=adc-dac
LibName14=memory
LibName15=xilinx
LibName16=microcontrollers
LibName17=dsp
LibName18=microchip
LibName19=analog_switches
LibName20=motorola
LibName21=texas
LibName22=intel
LibName23=audio
LibName24=interface
LibName25=digital-audio
LibName26=philips
LibName27=display
LibName28=cypress
LibName29=siliconi
LibName30=opto
LibName31=atmel
LibName32=contrib
LibName33=valves
LibName34=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_DCDC-ACDC-Converter_RevC_20Jul2012
LibName35=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_EN60617_13Mar2013
LibName36=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_EN60617-10_HF-Radio_DRAFT_12Sep2013
LibName37=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_ICs-Diskrete_RevD10
LibName38=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_ICs-Opto_RevB_16Sep2013
LibName39=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_Microcontroller_Philips-NXP_RevA_06Oct2013
LibName40=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_Socket-DIN41612_RevA
LibName41=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/Symbols_Transformer-Diskrete_RevA
LibName42=C:/Program Files/KiCad/share/kicad/library/contrib_symbols_dl1eic/SymbolsSimilarEN60617+oldDIN617-RevE8
LibName43=C:/Program Files/KiCad/share/kicad/library/hc11
LibName44=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName45=C:/Program Files/KiCad/share/kicad/library/74xx
LibName46=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName47=C:/Program Files/KiCad/share/kicad/library/actel
LibName48=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName49=C:/Program Files/KiCad/share/kicad/library/allegro
LibName50=C:/Program Files/KiCad/share/kicad/library/Altera
LibName51=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName52=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName53=C:/Program Files/KiCad/share/kicad/library/atmel
LibName54=C:/Program Files/KiCad/share/kicad/library/audio
LibName55=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName56=C:/Program Files/KiCad/share/kicad/library/bbd
LibName57=C:/Program Files/KiCad/share/kicad/library/bosch
LibName58=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName59=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName60=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName61=C:/Program Files/KiCad/share/kicad/library/conn
LibName62=C:/Program Files/KiCad/share/kicad/library/contrib
LibName63=C:/Program Files/KiCad/share/kicad/library/cypress
LibName64=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName65=C:/Program Files/KiCad/share/kicad/library/device
LibName66=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName67=C:/Program Files/KiCad/share/kicad/library/diode
LibName68=C:/Program Files/KiCad/share/kicad/library/display
LibName69=C:/Program Files/KiCad/share/kicad/library/dsp
LibName70=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName71=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName72=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName73=C:/Program Files/KiCad/share/kicad/library/gennum
LibName74=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName75=C:/Program Files/KiCad/share/kicad/library/icl7660
LibName76=C:/Program Files/KiCad/share/kicad/library/infineon
LibName77=C:/Program Files/KiCad/share/kicad/library/intel
LibName78=C:/Program Files/KiCad/share/kicad/library/interface
LibName79=C:/Program Files/KiCad/share/kicad/library/intersil
LibName80=C:/Program Files/KiCad/share/kicad/library/ir
LibName81=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName82=C:/Program Files/KiCad/share/kicad/library/leds
LibName83=C:/Program Files/KiCad/share/kicad/library/LEM
LibName84=C:/Program Files/KiCad/share/kicad/library/linear
LibName85=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName86=C:/Program Files/KiCad/share/kicad/library/maxim
LibName87=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName88=C:/Program Files/KiCad/share/kicad/library/memory
LibName89=C:/Program Files/KiCad/share/kicad/library/microchip
LibName90=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName91=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName92=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName93=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName94=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName95=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName96=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName97=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName98=C:/Program Files/KiCad/share/kicad/library/modules
LibName99=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName100=C:/Program Files/KiCad/share/kicad/library/motorola
LibName101=C:/Program Files/KiCad/share/kicad/library/motors
LibName102=C:/Program Files/KiCad/share/kicad/library/msp430
LibName103=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName104=C:/Program Files/KiCad/share/kicad/library/nxp
LibName105=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName106=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName107=C:/Program Files/KiCad/share/kicad/library/opto
LibName108=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName109=C:/Program Files/KiCad/share/kicad/library/philips
LibName110=C:/Program Files/KiCad/share/kicad/library/power
LibName111=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName112=C:/Program Files/KiCad/share/kicad/library/powerint
LibName113=C:/Program Files/KiCad/share/kicad/library/pspice
LibName114=C:/Program Files/KiCad/share/kicad/library/references
LibName115=C:/Program Files/KiCad/share/kicad/library/regul
LibName116=C:/Program Files/KiCad/share/kicad/library/relays
LibName117=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName118=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName119=C:/Program Files/KiCad/share/kicad/library/Sensor_Magnetic
LibName120=C:/Program Files/KiCad/share/kicad/library/sensors
LibName121=C:/Program Files/KiCad/share/kicad/library/silabs
LibName122=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName123=C:/Program Files/KiCad/share/kicad/library/stm8
LibName124=C:/Program Files/KiCad/share/kicad/library/stm32
LibName125=C:/Program Files/KiCad/share/kicad/library/supertex
LibName126=C:/Program Files/KiCad/share/kicad/library/switches
LibName127=C:/Program Files/KiCad/share/kicad/library/texas
LibName128=C:/Program Files/KiCad/share/kicad/library/transf
LibName129=C:/Program Files/KiCad/share/kicad/library/transistors
LibName130=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName131=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName132=C:/Program Files/KiCad/share/kicad/library/valves
LibName133=C:/Program Files/KiCad/share/kicad/library/video
LibName134=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName135=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName136=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName137=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName138=C:/Program Files/KiCad/share/kicad/library/zetex
LibName139=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName140=library/lm2596_adjustable_dcdc_stepdownmodule
LibName141=library/mosfetmotordriver
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
